### ISSUE TITLE
[Custom power-ups] Riding enemy when ducking is inconsistent

### ISSUE THREAD

**Issue by alesan99** [alesan99/mari0_ae#10]
"you should fix the offets for riding an enemy while ducking. Standing and then riding will be normal but ducking while riding will have the player spawn a block higher instead. Can you please fix that? It is pretty broken"

**Comment by WilliamFr0g** [comment]
Basically riding an enemy sticks the player relative to the top left corner of the enemy, so ducking will result in the player's feet being 0.75 blocks higher up when they spawn back in, making it as though they traveled upwards

**Comment by alesan99** [comment]
c9faa27b453d5e3be5c3eeddcb8a097b6654c364
