### ISSUE TITLE
Fix Shellmets bouncing certain enemies; shellmets not being removed after testing

### ISSUE THREAD

**Issue by alesan99** [alesan99/mari0_ae#100]
![GIF_18-05-2021_20-01-11](https://user-images.githubusercontent.com/8108710/119279883-0b3ea000-bbf4-11eb-8791-05eae2e0a262.gif)
- the editor doesnt remove them, so everytime you test a level, you receive a shellmet
- hitting a bullet bill with a shellmet from below sends them to space
- sleep fish can get stuck in hitting the shellmet

**Comment by LeanneTM** [comment]
reminder: this doesnt only happen to bullet bills, but other enemies like cheep cheeps (at times, sometimes they just keep in place), parabeetles, cannonballs and idk what else. id say, check more just in case to avoid a similar issue later

**Comment by LeanneTM** [comment]
addendum i wrote on the discord server -
all helmets can be kept in other levels after exiting editor. it happens after you exit a sublevel, it tries to persist the helmet but there isnt a check for when you exit the editor, so it keeps it in any level u go

**Comment by alesan99** [comment]
28319b120bd4e039920f26af82b821f28e82f4af
