### ISSUE TITLE
Gel blobs disappearing when entering funnels/portals

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#104]
When a stream of gel blobs enters a portal, or gets carried by a funnel, some of the gel blobs disappear. This is really annoying because some puzzles may require the player to carry gel through a funnel or through multiple portals, but a good 50-75% of the gel blobs have disappeared on their own, making it more annoying to coat the surface you want in gel.

**Comment by alesan99** [comment]
This is the intended behavior, the max gel limit is reached almost immediately without it and it makes coating surfaces even more annoying.

**Comment by alesan99** [comment]
28ebc6a0646318244a537c492c8b866a54d7b750
