### ISSUE TITLE
Cubes don't bounce off of walls coated in Repulsion Gel

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#108]
Cubes bounce on Repulsion Gel coated floors, which is to be expected, however, they do not bounce off of walls coated in Repulsion Gel. Extending this behaviour to walls would make the gel's effect on cubes more consistent, and open up new puzzle possibilities.

**Comment by alesan99** [comment]
50d697335d11af3c7ca9abd522750598192580c5
