### ISSUE TITLE
Adhesion Gel gravity-changing behaviour doesn't work properly with cube/gel droppers

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#112]
Mario will still "fall" in the direction that the Adhesion Gel sent him, but if he "lands" on a box dropper or gel dropper, he doesn't switch back to falling down again, he will press up against the dropper, still obeying the Adhesion Gel's gravity rather than falling back down again.

**Comment by alesan99** [comment]
1adb0c2099df130b4e73220e5f3709d5eb72b42a
