### ISSUE TITLE
Portal element sound effects

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#114]
Portal elements currently have no sound effects, and I think it would make them a lot more satisfying to use.

- Push buttons need sounds when pressed/unpressed
- Floor buttons need sounds when pressed/unpressed
- Faith plate sounds for flinging objects
- Funnel sounds when entering/exiting funnels
- Repulsion gel sounds when walking onto/off of the gel, and bouncing on the gel
- Propulsion gel sounds when walking onto/off of the gel
- Adhesion gel sounds when walking onto/off of the gel
- Objects entering fizzlers make a fizzle sound

All of these sounds can be extracted from Portal 2's game files. I can retrieve them myself if needed.

**Comment by Critfish** [comment]
[portalsounds.zip](https://github.com/alesan99/mari0_ae/files/6604061/portalsounds.zip)
@alesan99 
I have retrieved most of the sound effects. There might be some I'm forgetting, but this is the vast majority of them. Includes all gel sound effects(including walking onto/off of the gels, bouncing on blue gel, and blue gel painted cube bounce sound), faithplate sounds, floor button and push button sounds, laser catcher activating/deactivating sounds, sounds for enabling/disabling fizzlers, object fizzling sounds, and the pick up portalgun sound.

Interesting note: Old Aperture floor buttons and push buttons have their own unique sound effects. In AE, modern elements and old aperture elements are defined via spritesets. In order for modern and old aperture elements to have unique sounds, there would need to be multiple sound effects for them, played based on the chosen spriteset(perhaps all applicable sounds could be numbered 01-04 for each spriteset?)

I haven't tested all the sounds in-game, so some may be too loud/too quiet compared to the rest of the game. Adjust them manually if needed.

**Comment by Aid0nModder** [comment]
Critfish i know you are very passionate about this but holy shit that is a lot of sounds

**Comment by alesan99** [comment]
I don't think I'll add these by default, but it would be a good addition in #126

**Comment by Critfish** [comment]
> I don't think I'll add these by default, but it would be a good addition in #126

Do you mean just adding blank sounds for them by default?

**Comment by alesan99** [comment]
> > I don't think I'll add these by default, but it would be a good addition in #126
> 
> Do you mean just adding blank sounds for them by default?

Basically, but without actually adding any blank sound files
