### ISSUE TITLE
A fix for "portal peeking"

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#117]
Due to the way portal shots work, it's possible to stand inside a portal, or in front of an emancipation grill, fire a portal, then quickly move through the portal or grill before the portal shot lands and creates a new portal. This can be used to cheese certain puzzles, or completely bypass emancipation grills.

This can be fixed by making portal shots connect instantaneously upon pressing the fire button, rather than having an actual projectile, like in Portal 2. This likely wouldn't affect any existing mappacks, but if that's a concern, it could be included as a per-mappack setting.

Alternatively, emancipation grills could destroy all existing portal shot projectiles upon the player touching them, making it impossible to bypass emancipation grills that way. This wouldn't fix traditional portal peeking, but it would prevent players from bypassing emancipation grills.

**Comment by alesan99** [comment]
b75b6f2931429e5e0f982dd1841a868df9657157
