### ISSUE TITLE
Repulsion Gel doesn't bounce the player if they jump while standing on it

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#120]
In Portal 2, the gel will bounce you if you jump while standing on top of it, or when landing on it. In Mari0, the latter is true, but the former is not. Jumping while standing on the gel will only create a standard-height jump, and will only start bouncing you high once you fall down and land on the gel again. This makes using repulsion gel quite finicky.

**Comment by alesan99** [comment]
This is intentional.
When using portal physics it behaves like portal 2.

**Comment by Critfish** [comment]
> This is intentional.
> When using portal physics it behaves like portal 2.

No it doesn't. You still jump at the normal 1.5 block height.

**Comment by alesan99** [comment]
> No it doesn't. You still jump at the normal 1.5 block height. You only begin bouncing high once you land back on the gel.

Yes it does though. 
![GIF](https://user-images.githubusercontent.com/8108710/120890414-15837580-c5c8-11eb-9f4c-6b995cfcb88b.gif)
![Capture](https://user-images.githubusercontent.com/8108710/120890462-68f5c380-c5c8-11eb-8766-67da1d15646a.PNG)

**Comment by Critfish** [comment]
I must've been using an outdated version, sorry for the annoyance.
