### ISSUE TITLE
Adhesion Gel is not coating ceilings

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#123]
![image](https://user-images.githubusercontent.com/58682909/120910179-d2a2ca00-c6bb-11eb-99cf-96ae152c865f.png)
Self-explanatory

**Comment by WilliamFr0g** [comment]
![image](https://user-images.githubusercontent.com/83377256/120916498-f3493080-c677-11eb-9652-1bc7a2b098bc.png)
It seems to work for me

**Comment by Critfish** [comment]
It's an issue in the current in-development build. Alesan fixed adhesion gel with light bridges, maybe he accidentally broke this in the process.

**Comment by alesan99** [comment]
9f1fc3cdaa7e04591072209057609eeec50b4209
