### ISSUE TITLE
Repulsion Gel jump-bouncing behaviour doesn't work correctly on light bridges.

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#124]
![lightbridge](https://user-images.githubusercontent.com/58682909/120920092-41a01300-c6fc-11eb-93e6-7443e0727947.gif)
While this issue has already been fixed for standard floors, it still does not work correctly on light bridges.

**Comment by alesan99** [comment]
9f1fc3cdaa7e04591072209057609eeec50b4209
