### ISSUE TITLE
Game crash when selecting multiple linkable entities + any power line entity, and right-clicking the power line

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#129]
Exactly what the title says. To reproduce the bug, use the selection tool to select multiple linkable entities(eg. portal elements), with at least one of the selected entities being a power line. Right click the power line, and the game will crash.

![image](https://user-images.githubusercontent.com/58682909/121142090-c9ac2700-c87a-11eb-91ba-5f2e1dd6bdb8.png)

**Comment by alesan99** [comment]
fddf8c52f6421293981f212ac3011e6296347b98
