### ISSUE TITLE
bomb don't light when hit from below

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#130]
When you hit a bomb on a block it dies when it should just turn into a lit bomb
![GIF 10-06-2021 17-37-03](https://user-images.githubusercontent.com/71894636/121563815-b0d67980-ca12-11eb-900a-7d20637df458.gif)

**Comment by alesan99** [comment]
016d0be884c8202d6f3d768e9236dada65d51a59
