### ISSUE TITLE
"dontGiveCoinsToPlayer", "collectsKeys", "collectsCollectables"

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#131]
- ~~bomb explosions stay on tracks, it looks weird~~
- ~~shells should collect coins (ik it wasn't in smb but it should be an option)~~
- ~~shells should be able to press p-switches and !-switches.~~
- on the similar note, I have some coin properties for custom enemies would be cool
  - ~~"collectsCoins": picks up coins and gives to player~~
  - "dontGiveCoinsToPlayer": doesn't give coins to the player when picked up
  - "collectsKeys"; collects keys.
  - "collectsCollectables": when true picks up all collectables but if an array it only picks up ones that are true, for example...
        "collectsCollectables": [true, false, false, true] will only pickup collectables with id 1 and 4.
- ~~cannonball cannons can't collide with red seesaws.~~

**Comment by alesan99** [comment]
#64

**Comment by alesan99** [comment]
e43e37276e847ca48f8a1eceffca84838a1cb4f8

**Comment by WilliamFr0g** [comment]
You can also freeze bomb explosions

**Comment by alesan99** [comment]
> You can also freeze bomb explosions

Not as far as I can tell. I remember you already told me this a while ago, so I must have fixed it then.

**Comment by alesan99** [comment]
8a9184d9dc34ffdf8d1ca35b03bcd2b39fa8b7af
The other properties aren't too useful I think
