### ISSUE TITLE
Infinite Loop Bug with Custom Enemy Transform and Tile with Water Property

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#132]
(i hope title isnt misleading or way too long)
basically, if you have a tile with the water property and you get a custom enemy to transform when touching it (trigger: water), it will freeze the game in what id call a infinite loop.
thing is, it works perfectly on risingwater but not with a water tile..

this loop thing happens when you use a delay of 0 in a customtimer as well, but thats not a problem from the game. :p

**Comment by alesan99** [comment]
Cannot replicate, probably an issue with the enemy itself
![GIF](https://user-images.githubusercontent.com/8108710/121776162-f26d3e80-cb50-11eb-9da1-5d35033f1737.gif)

**Comment by LeanneTM** [comment]
nevermind, i forgot to mention i transformed enemy to itself when this happened but yeah. i hope infinites can get at least fixed in some sort of failsafe though

**Comment by alesan99** [comment]
There's no point, the game is doing exactly what it's told to do

**Comment by LeanneTM** [comment]
alrighty! 👍🏻
