### ISSUE TITLE
Background tiles act weird when using modified screen width/height nitpicks

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#133]
Place background tiles in a level with modified screen width/height nitpicks enabled, and scroll the camera along. This will cause background tiles to behave in a weird, glitchy manner. They move along with the player, but snap back to their original position again once 1 tile width has been scrolled, repeating for every tile width the player scrolls the screen.

**Comment by alesan99** [comment]
Already fixed a few days ago
