### ISSUE TITLE
Block-like enemies and stars don't mix

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#135]
Been an issue for a while (I think i have brought it up before) A fix would be appreciated.
![GIF 15-06-2021 11-58-43](https://user-images.githubusercontent.com/71894636/122041771-35d5e000-cdd1-11eb-8339-34ef03e498f8.gif)

**Comment by LeanneTM** [comment]
i found this accidentally while trying to code a custom enemy question block (my most recent issue says why) and making it stop using a customtimer which sets static to true after a certain delay. apparently, custom enemies dont stop in the exact same time so sometimes mario slides like this or collides with a super duper hyper small subpixel depending of where youre walking...

**Comment by alesan99** [comment]
a88341dbecebea3f4246e0431979efc0bea00312
