### ISSUE TITLE
Question Block Sprout Animation

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#137]
was making a custom coinblockanimation enemy until i hit the question block from below.. it gave me the typical slow sprout animation which ruins the idea i was going for. so, to not recreate the question block for this alone, i proposed this: being able to change the sprout animation.

the thing can be like this: a tickbox which lets you change whenever the object inside the question block does the "go up" animation or just not, so it immediately comes out.. or maybe you can go fancy and add a spawn dropdown like the spawner entity. :p

**Comment by alesan99** [comment]
5b69360cd0322a7f531056e39cb5f2132592f7c5
