### ISSUE TITLE
Sucky tube (forgot the name) softlock

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#138]
![GIF 16-06-2021 22-50-01](https://user-images.githubusercontent.com/71894636/122299085-729af780-cef5-11eb-8ce5-188712b5530d.gif)

**Comment by LeanneTM** [comment]
what a  n i c e  name there :V

**Comment by alesan99** [comment]
This should probably be up to the map creator, and the portal gun should be available most of the time when suck tubes are being used
