### ISSUE TITLE
Missing pixel

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#139]
I can't edit images on GitHub apparently so you're gonna have to do it :/

![image](https://user-images.githubusercontent.com/71894636/122422198-e0423480-cf84-11eb-95c8-1acfa6da9945.png)

**Comment by LeanneTM** [comment]
lmao, youll lose it even more as soon as i tell u coinblockanimation has incorrect colors (not fceux).

**Comment by alesan99** [comment]
#141
