### ISSUE TITLE
bouncyforce not working correctly

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#140]
When i set bouncyforce and use both left and right, for some reason if the speed is positive the left side works but the right side doesn't, but when it's negative the right side works but the left doesn't. not sure what the issue is.
![GIF 17-06-2021 23-25-33](https://user-images.githubusercontent.com/71894636/122479655-5cf40380-cfc3-11eb-877c-b72fb7d2b68a.gif)

**Comment by Aid0nModder** [comment]
Ok i just had to set "dontstopmario" for 0.1 seconds to fix it. no idea how this is happening.

**Comment by WilliamFr0g** [comment]
Judging from the code, it's only ever supposed to be positive. It's probably something with the bully transforming. Maybe make it static and see what happens
