### ISSUE TITLE
Way for snake block to start moving backwards

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#142]
In SMM2 snakeblocks can start moving in these 6 directions, the only one i can see myself using a lot is the one going backwards.
Not sure how hard it will be to add but should be considered.

![image](https://user-images.githubusercontent.com/71894636/122565382-52c31b00-d03e-11eb-90ef-4a816c09431f.png)

**Comment by LeanneTM** [comment]
sounds like pain lol
but if alesan does it, my respects :3
