### ISSUE TITLE
Way for "supersizeproperties" to change position

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#150]
Right now if you wanna change it's position you have to use a custom timer. A way for "spawnoffsetx" and "spawnoffsety" to work would be great.

**Comment by Aid0nModder** [comment]
Ok after looking at the cide i saw that "supersizeoffsetx" existed but no "supersizeoffsety" (the one i needed) :/

**Comment by alesan99** [comment]
047849fe8f9fcca202214857e0524f0556275ef6
