### ISSUE TITLE
Bob-omb explode when crushed by munchers, thwomps killed by star

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#152]
(I might add more later when i find some)

**Bombs**
- They can't be lit by lava bubbles (entity and custom enemy)
- They don't explode why a muncher crushes them.

**Thwomp**
- Can't be killed by star

And all enemies still can't use noteblocks.

Also plants still have their down versions in the editor... despite being a right click now.

**Comment by alesan99** [comment]
> Also plants still have their down versions in the editor... despite being a right click now.
Intentional because its convenient

**Comment by alesan99** [comment]
a105689dd5ca9465fe80902a6f9884749aa3569c
