### ISSUE TITLE
Tiles not drawing properly.

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#154]
Not sure if this is a new bug or old issue but it should be fixed.
![GIF 25-06-2021 12-33-03](https://user-images.githubusercontent.com/71894636/123419009-aa6b0480-d5b1-11eb-9958-d3d63cb00e29.gif)

**Comment by alesan99** [comment]
Are you on the latest commit?

**Comment by Aid0nModder** [comment]
No, just updated and it's fixed now

**Comment by alesan99** [comment]
Ok cool.
