### ISSUE TITLE
Allow backgrounds to use subfolders, like custom enemies

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#158]
![image](https://user-images.githubusercontent.com/58682909/123625773-44031200-d84f-11eb-9da9-57e7fbac10c3.png)
In mappacks with a lot of different backgrounds, multi-layered backgrounds, and backgrounds with JSONs, the backgrounds folder can very quickly become very cluttered and messy, and can be annoying to work with. Being able to sort them into subfolders would make working with custom backgrounds a lot cleaner.

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/429
