### ISSUE TITLE
Host files to download in this repo's releases page instead of Dropbox

### ISSUE THREAD

**Issue by NNBnh** [alesan99/mari0_ae#164]
Here are some advantages:
- Host for free
- People can easily find and download any version of the mod
- Will notify everyone that watch this repo if their is a new release
- If #163 was merge we can:
  > - [X] Move [Change List](https://github.com/NNBnh/mari0_ae#-features) to [this Github repo's releases page (if it later have one)](https://github.com/alesan99/mari0_ae/releases)

**Comment by Aid0nModder** [comment]
W- what????

**Comment by alesan99** [comment]
Yes I was planning on doing that, but it will also be on dropbox because I have a nice workflow with it.
