### ISSUE TITLE
[Android] JSON Error Screen Issue

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#181]
![Screenshot_20210723-205309](https://user-images.githubusercontent.com/83039977/126851125-7ae5703b-e9c7-4b3c-9f62-6b37efc27759.jpg)
so, while i was doing things on phone, i did an oopsie, but when i wanna press any of the buttons; i cannot. the controls here obscure the options, forcing me to reopen the app just to get it away.. essentially making the ignore and retry buttons useless

this isnt a big issue, but may become annoying when you need to check things up

**Comment by Aid0nModder** [comment]
#182
