### ISSUE TITLE
bug with the slopes

### ISSUE THREAD

**Issue by dc249** [alesan99/mari0_ae#187]
![Screenshot 2021-07-25 154714](https://user-images.githubusercontent.com/85324387/126893391-4dd3b1cc-997c-4515-aacc-46223f7ed82d.jpg)
I have found this bug while I playing Mari0 AE on computer and I want to shoot a portal beside the slope

**Comment by Aid0nModder** [comment]
This is just slopes being slopes, don't expect a fix

**Comment by alesan99** [comment]
This is known. Slopes can only be fixed with a complete rewrite, which may or may not ever happen.

**Comment by alesan99** [comment]
8d584fc67b2b319a7e213b1c06eaa9a3be38b9dd
