### ISSUE TITLE
Animation ideas

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#188]
Trigger
- on mappack load: only triggers once when the mappack is loaded

Condition
- If number exists / not exists: checks if an animation number exists or not.

Actions
- Walk to X: like animate to walk but to a specific position.
- make player up: like holding the up button
- make player down: like holding the down button (could be useful for vine animations)
- hide/show hud / change hud  transparency: self explanatory, could be useful for cutscenes.
- hide/show android buttons / change android button transparency: self explanatory, could be useful for cutscenes.

**Comment by alesan99** [comment]
> Condition
> 
> * If number exists / not exists: checks if an animation number exists or not.

'number = *blank*' checks if it doesn't exist
checking if it exists isn't as conventional, but you could do 'number > -999999'

**Comment by Aid0nModder** [comment]
oh thanks

**Comment by WilliamFr0g** [comment]
Triggering on mappack load can be done pretty easily with number logic. Have it run only when a number doesn't exist, then have it change that number.
