### ISSUE TITLE
Platform (FPS?) Issue

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#189]
it happened to be on both pc and mobile, so basically, player falls from it when standing on a platform and it goes upwards at a fast or weird speed (happened to me on a custom enemy platform on mobile too).

may need to investigate what happens on certain places. i dont have the best pc or phone, so it can help people with same problem ig... unless its a me thing

example screenshot i took recently where i use tracked fast and it goes up:
![Screenshot_20210725-131825](https://user-images.githubusercontent.com/83039977/126906177-2929b366-4eda-4c52-940e-771a06d0fa63.jpg)

**Comment by Alexis0159** [comment]
happens when mario jumps if the platform moves at full speed

**Comment by alesan99** [comment]
da729b713f9279aaba6c22eaa6d9b8c635bc2502
