### ISSUE TITLE
Inaccurate palette, Piranha plant sprite placement, SMB1 level layout slight inaccuracies

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#190]
idk how important is this (its more of very low priority) but several things in both the smb1 mappack and images in mari0 are either outdated or incorrect, and deserves an update after years of being untouched(?).

here are some of them:

IMAGES:
- incorrectly colored images [ex: coinblockanimation, coinblock (theres 2 browns and yellows), custom enemy parakoopa having brighter orange than hammer bro, etc.]
- ~~missing proper spriteset coloring (ex: question block should have blue ? underwater, pink and normal squid is missing rest of goomba pals, cheep cheeps are entirely missing other pals, etc.)~~
- misplaced piranha plant (missing entire bottom row of pixels, makes topmost pixels pop out of pipe), cropped peach (missing entire bottom row of pixels, making it harder to customize due to strange image size), maybe others im forgetting
- ~~some items should have spritesets too (as in, color palettes, the hammer suit should be gray in castle levels for example)~~

MAPPACK:
- ~~strangely varied level sizes [some arent even 1 screen such as bonus underground zones (16 blocks wide)]~~
- ~~coins shouldnt use tiles anymore, since coin entity exists now (thats just me though)~~
- minor inconsistencies on repeated levels(?)
- ~~7-4 maze is broken (doesnt seem to work here, idk if it can even be fixed at all)~~
- ~~remove weird red square block on 8-4 mazes~~, one of 8-4 sections is misplaced, missing piranha plant in 8-4 sublevel 1 and warp zone back to beginning in final sublevel
- ~~maybe others i need to remember or recheck~~

i can help you with all of this if you want, at least to update these small things that dont matter but help on shaping the non-dlc base game.

**Comment by LeanneTM** [comment]
p.s - heres an strange occurence on smb1: basically, underwater hit blocks have their own color.. something mari0 skipped entirely, making it the normal overworld brown. ill not take it in consideration since id prefer for this to be done if critfish's suggestion (custom hit blocks) is done, so smbtiles hit blocks can get deprecated.

**Comment by WilliamFr0g** [comment]
No way this will be "fixed", accuracy to smb1 is not and never was high priority
