### ISSUE TITLE
"bounceforcerandom" doesn't work

### ISSUE THREAD

**Issue by WilliamFr0g** [alesan99/mari0_ae#191]
It doesn't work

**Comment by Aid0nModder** [comment]
found it, it is set to math.floor, not math.random
![image](https://user-images.githubusercontent.com/71894636/127012669-01699db6-ccee-402d-8bb3-ad010a52ce6d.png)

**Comment by alesan99** [comment]
925f4403a87a7784307166fa848e07553f055fce
