### ISSUE TITLE
"spawnonload" Bugs with Spritesets

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#206]
idk if this happens with everything or only a few things using spawnonload but, in todays case - i used spawnonload on a custom enemy called "coin" (4 frames, with spritesets, most of them differently colored) and smth happened.

detailed explanation below:
when i entered the sublevel i did thru the editor (a simple bonus zone), it was fine, but when i quick tested and entered a pipe that leads to said sublevel, the coins remained golden despite spriteset on the editor set to underground (the coins should be blue). then, when i exit the editor, the coins become blue like they should be...

so i did a quick investigation and apparently this isnt a simple bug, it extends a bit - when i change spritesets from overworld to underground (for example) and quick test, coins remain gold... whats the problem? i made em also disappear with a spark, which shares same spriteset coloring as the normal coin... and the spark was blue...

to resume:
something is happening between spawnonload and spritesets that makes em act weird (maybe normal gameplay suffers from this too). needs to be investigated in the code

**Comment by alesan99** [comment]
3b45f4096bae8df224962cfd23d566b806bc1906
