### ISSUE TITLE
spawner connect to blue coin

### ISSUE THREAD

**Issue by dc249** [alesan99/mari0_ae#207]
When I connect a spawner to blue coin like this
![Screenshot 2021-08-03 071112](https://user-images.githubusercontent.com/85324387/127938722-1bfc9eed-d4ce-4848-9085-a686628ef43a.jpg)
and this is happened while I eat the blue coin
![Screenshot 2021-08-03 071210](https://user-images.githubusercontent.com/85324387/127938875-63c3bd56-e423-4724-916c-488253e0286c.jpg)
please fix it

**Comment by WilliamFr0g** [comment]
That happened because you linked the collectable to itself

**Comment by dc249** [comment]
Thanks

**Comment by WilliamFr0g** [comment]
You should probably close the issue
