### ISSUE TITLE
Portal Mappack is world 2-1 is broken

### ISSUE THREAD

**Issue by Ch1216** [alesan99/mari0_ae#213]
Portal Mappack world 2-1 is unbeatable due to the speed gel not reaching enough for the player to be able to jump to the the bounce gel

Mari0 1.16

https://user-images.githubusercontent.com/68875386/132111400-4f016807-65d0-4ac5-90e7-2cea1e47108b.mp4

Mari0 Alesan99's entities 13d (which I think is the latest update)

https://user-images.githubusercontent.com/68875386/132111498-a694ea92-6f47-464e-8ccf-25e16ed46f42.mp4

**Comment by WilliamFr0g** [comment]
The issue does not render the level unbeatable, however yes there is a problem with gel placement.
![Portal 2-1](https://user-images.githubusercontent.com/83377256/132141453-bf1e6136-ab34-46e4-94f1-625e0c24c55f.gif)
