### ISSUE TITLE
FourByThree Nitpick Problem in Mobile

### ISSUE THREAD

**Issue by LeanneTM** [alesan99/mari0_ae#214]
so um, i activated it in mobile as soon as i knew of it and...
![Screenshot_20210905-230455](https://user-images.githubusercontent.com/83039977/132150659-58215612-0e5d-4841-b1b4-155b014e03cc.jpg)
i think you may need to fix this. the right half of controls are inaccessible, but hopefully i was able to touch the options to activate letterbox, which doesnt help much either:
![Screenshot_20210905-230509](https://user-images.githubusercontent.com/83039977/132150689-0d52b485-3965-4f1e-8b2b-f42e1d96f677.jpg)

**Comment by Aid0nModder** [comment]
4:3 wasn't really made for mobile, thankfully now alesan rewrote android controls it should be an easier fix

**Comment by Aid0nModder** [comment]
https://github.com/alesan99/mari0_ae/pull/310
