### ISSUE TITLE
Go in pipe don't need floor

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#222]
If you do not understand me:
![Bug 2](https://user-images.githubusercontent.com/85324387/134887024-afa47152-4b62-4618-a614-06fe4fa7ab18.gif)

**Comment by WilliamFr0g** [comment]
This is an old glitch, fixing it might cause backwards compatibility issues

**Comment by MinDC249** [comment]
Oh, I don't know. Sorry.😓
