### ISSUE TITLE
Burners shouldn't be portal-able

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#229]
![Bug 6](https://user-images.githubusercontent.com/85324387/135709852-7385adb9-f466-4bd3-b2a8-bf54c9dbac6b.gif)

If you are trying to reproduce this bug
![Screenshot 2021-10-02 155308](https://user-images.githubusercontent.com/85324387/135709885-d90712ae-8263-4ee5-a9bd-f21d496ec050.jpg)
 
you need to do this
![Screenshot 2021-10-02 155303](https://user-images.githubusercontent.com/85324387/135709903-fa43eb56-dfe4-45b3-a513-f6f6cd772d2c.jpg)

then close the portal when the fire is big

**Comment by alesan99** [comment]
da1987eddc8d62e265c1a0a0c5bc6763fd840fbc
