### ISSUE TITLE
Can't destroy cubes if they touch Mario's head 

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#247]
![Bug 10](https://user-images.githubusercontent.com/85324387/137060290-9988cb34-d07f-4803-8941-312f49b741c3.gif)

**Comment by WilliamFr0g** [comment]
It doesn't have anything to do with Mario specifically. I think it's because collisions reset speedy to 0, and the emancipation check determines distance traveled by the object's speed, so it thinks the object didn't move anywhere even though it did.

**Comment by MinDC249** [comment]
I figured out that I use "vision" instead of "version" for a long time

**Comment by alesan99** [comment]
c20a64f8687c6d714015e54780541b8935fcc6f0
