### ISSUE TITLE
Mario can go through some block by wind

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#248]
![Bug 11](https://user-images.githubusercontent.com/85324387/137064408-a1447c57-ea56-4338-85ce-288ed4fd57db.gif)

**Comment by WilliamFr0g** [comment]
Wind doesn't use speed or physics, it just doesn't move him if there are tiles in the way

**Comment by alesan99** [comment]
ed14ae89792efe5c27dae5dfe29a908e17b0cdd6

**Comment by MinDC249** [comment]
Hey, not done yet, it still has some blocks can go through.

**Comment by MinDC249** [comment]
Ice block

**Comment by MinDC249** [comment]
Oh OK, but you still should fix the ice block and muncher (sorry because I say after you fixed)
