### ISSUE TITLE
(Joke suggestion) change ceilblocker to '--most simple entity ever'

### ISSUE THREAD

**Issue by greatbritdan** [alesan99/mari0_ae#249]
It's been this way for years now, give it the recognition it deserves
![1](https://user-images.githubusercontent.com/71894636/137209971-cafc649e-3d80-40da-b914-5e7da486b72f.PNG)
![2](https://user-images.githubusercontent.com/71894636/137209978-1a9f2725-2e8a-418a-b9cb-39ac23ea6093.PNG)

**Comment by MinDC249** [comment]
Huh, it simple than I think
