### ISSUE TITLE
Laser crash the game when Mario touch it on the top of screen

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#270]
(the place that we can’t see because it is to high)

**Comment by MinDC249** [comment]
![Screenshot 2021-10-30 165439](https://user-images.githubusercontent.com/85324387/139528386-ae66e408-1d98-4bb0-acbf-814b28001f1d.jpg)

**Comment by alesan99** [comment]
Got it, thanks.
Only happens if the player's hitbox is tall enough.
fcd6b757dda5217a736afd06be47dc157287b0b2

**Comment by MinDC249** [comment]
This is a big bug and it is alive for 9 years 😶 (From original game)

**Comment by alesan99** [comment]
> This is a big bug and it is alive for 9 years 😶 (From original game)

It's already been fixed, i linked the fix

**Comment by MinDC249** [comment]
> It's already been fixed, i linked the fix

Just say to know
