### ISSUE TITLE
Weird seam issue on box dropper

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#284]
Not sure it's fixable but i sure hope it is.
![GIF 29-10-2021 16-58-55](https://user-images.githubusercontent.com/71894636/139466493-ed048116-41e9-4699-94a1-a3701056d7c5.gif)

**Comment by alesan99** [comment]
Oh it's actually not the quad issue I thought it was, I just needed to round the y position.
d80f4adfdc5b1408b7a0a291792b5d6f9c25c4d2
