### ISSUE TITLE
Switch blocks should only register once if multiple are hit at the same time

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#285]
Just a thing I want you to know that if two players or more hit the on/off block at the same time, the on/off block just change the color once time in SMM2

**Comment by WilliamFr0g** [comment]
This is incredibly unimportant

**Comment by alesan99** [comment]
Something like this would be needed for thwomps to be able to hit mutliple switch blocks at the same time, and some smm2 puzzles may require it, but its pretty unimportant as it is.

**Comment by alesan99** [comment]
Implemented only for when the blocks are hit on the same frame. Works with thwomps but may be hard to do in multiplayer 742c9bf222e4f6a306a29df0314b20893a858af7

**Comment by MinDC249** [comment]
> This is incredibly unimportant

I know 🙃

**Comment by alesan99** [comment]
> > This is incredibly unimportant
> 
> I know 🙃

Since you've been making a lot of issues try to stick to the important ones.
