### ISSUE TITLE
Door's sprite should change the location when use maze

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#286]
![Bug 16](https://user-images.githubusercontent.com/85324387/139519196-300d98f9-13bd-4878-bccd-30b7372291a3.gif)
###

**Comment by MinDC249** [comment]
Another small bug I was talked about with William
![Bug 17](https://user-images.githubusercontent.com/85324387/139519261-0628f62f-9bbb-4181-bed6-a4ec92e96dc7.gif)

**Comment by WilliamFr0g** [comment]
Most entities don't work with mazes

**Comment by alesan99** [comment]
Mazes were only implemented for the SMB mappack, so many entities were left out intentionally by maurice and myself. The way mazes work makes it so each individual linkable entity would have to be carefully adapted, which would take an extreme amount of time.
