### ISSUE TITLE
Make Music Not Restart When Going To A Sublevel (Please)

### ISSUE THREAD

**Issue by AmyTheCat178** [alesan99/mari0_ae#29]
If you use the same music in different sublevels, it will restart when you go from one area to another. It would be nice if there was a way to make the music not restart, maybe a tick box after the music or even a word in the music's name.
(e.g.: "underground-norestart") and you put it in every map that uses it.

**Comment by alesan99** [comment]
d42d680564af4104fb8bee8971aa2729ba803d68
