### ISSUE TITLE
Crash when changing background RGB color

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#291]
When I delete all the numbers in a background color box to change its value, I get this error:
![Screen Shot 2021-11-01 at 12 49 46 PM](https://user-images.githubusercontent.com/63458530/139708949-5c71bcc2-6587-47b1-a481-65d704caf322.png)

**Comment by alesan99** [comment]
Regression caused by https://github.com/alesan99/mari0_ae/commit/0e51914a0a994f900192525b07b8466516c0acfb

**Comment by alesan99** [comment]
7306c93107a0a9a8b821034e29ebfc281ba15d95
