### ISSUE TITLE
Switch Portal Gun Animation (Suggestion)

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#299]
An action for animations that allows the game to switch what portal gun the player is holding. (between all the options available in the "main" tab)

**Comment by MinDC249** [comment]
You already can do that with portal gun pedestal

**Comment by MoonstreamJustNotInSpace** [comment]
But I can't do that on the spot, the pedestal is immobile, can't remove the portal gun.

**Comment by MoonstreamJustNotInSpace** [comment]
Also, the pedestal is one-use per map load.
