### ISSUE TITLE
(Suggestion) recording?

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#301]
Two other games I've played (Nimbatus and MegaMaker) have GIF recording features, which are kind of cool. Adding that is the suggestion

**Comment by Aid0nModder** [comment]
not likely, just use GIFcam

**Comment by MinDC249** [comment]
Yeah Aidan has many good solutions so just keep listening to him

**Comment by alesan99** [comment]
The game engine does not have any support for encoding gifs or videos
