### ISSUE TITLE
Increase timer slider width for smaller numbers when typing

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#302]
Would it make sense for the timer to have a text box instead of a slider for time setting? It would be really useful, as the timer is effectively a falling pulse extender.

**Comment by MinDC249** [comment]
Right-click the slider and you will see

**Comment by MoonstreamJustNotInSpace** [comment]
Still, the issue is that it can only be multiples of 0.1, meaning that something requiring 0.16 seconds of timing (specifically, an animated tile sequence) can't use timers.

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/471
