### ISSUE TITLE
(Suggestion) Microchips?

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#303]
A microchip could be useful. Maybe using another menu like the animation menu, but with logic stuff instead? Maybe just a smaller area where you could build things, and then copy/paste without disconnecting blocks?

**Comment by MoonstreamJustNotInSpace** [comment]
The smaller area might be better, as then you could use stuff like custom enemies or other mechanisms.

**Comment by Aid0nModder** [comment]
Would be a lot of work and VERY buggy. so unlikely, maybe in a V13.1 when and if it's made

**Comment by alesan99** [comment]
Would be better addressed with object link support or custom enemy linking
