### ISSUE TITLE
Hold up button when carrying an enemy will make Mario carry it by back

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#304]

**Comment by WilliamFr0g** [comment]
What?

**Comment by MinDC249** [comment]
> What?

This is the true, Pineapple

**Comment by MinDC249** [comment]
Also hold down when small

**Comment by MinDC249** [comment]
> Hold up button when carrying an enemy will make Mario carry it by back
> Also hold down when small

Just happen when use classic cheat or in main tab

**Comment by alesan99** [comment]
3b45f4096bae8df224962cfd23d566b806bc1906
