### ISSUE TITLE
(Suggestion) Copy-Paste/Selection/Objects move saves wire connections within

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#308]
Circuits are currently a pain to move, because you have to reconnect everything. Would it be possible to retain within-selection connections so they would be easier to use?

**Comment by Aid0nModder** [comment]
i can already see 100 problems with this, link code is cancer so this is very unlikely

**Comment by MoonstreamJustNotInSpace** [comment]
Gotcha.

**Comment by WilliamFr0g** [comment]
#359

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/405
