### ISSUE TITLE
Bullettime can slowdown everything even title screen, options menu and select mappacks

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#314]

**Comment by WilliamFr0g** [comment]
Alesan doesn't fix bugs with cheats

**Comment by MinDC249** [comment]
#246

**Comment by MinDC249** [comment]
Just do like SE does, this is very easy fix

**Comment by Aid0nModder** [comment]
> Just do like SE does, this is very easy fix
do you mod mari0???? how can you tell it's easy

the bug you showed crashed the game. that is why it was fixed.

**Comment by MinDC249** [comment]
> > Just do like SE does, this is very easy fix
> 
> do you mod mari0???? how can you tell it's easy the bug you showed crashed the game. that is why it was fixed.

Yes, but not good as you, William and Alissen369

**Comment by MinDC249** [comment]
> that is why it was fixed

Wait, so why I still have that bug

**Comment by alesan99** [comment]
d75b9f8aef4a77d876b220d987af7aa560f353f2
