### ISSUE TITLE
Something doesn't right with mappack, online mappack and alesan/mappack folder

### ISSUE THREAD

**Issue by MinDC249** [alesan99/mari0_ae#317]
I don't know why but this bug makes William's Mari0 Paint mappack mix with Aidan's The Hidden One mappack (MPaint with THO's fonts)

I just put the un-zip Mari0 Paint map in mappacks folder and .zip The Hidden One in onlinemappack folder
attention: I change the mappack save location to alesan/mappack and I have put a .zip Mari0 Paint into onlinemappack folder but it doesn't appear in select map

(Too hard to explain so:
![Bug 19](https://user-images.githubusercontent.com/85324387/141236092-bc04d87e-b66e-4e9b-b196-972145ef3784.gif)
)

**Comment by slambo311** [comment]
You should probably bring this up with William and Aiden, not Alesan.

**Comment by MinDC249** [comment]
Two map got mix so that is game’s reading code bug

**Comment by slambo311** [comment]
First of all, your grammar is trash, you should pay attention in English class.
Second of all, don't jump to conclusions, it could be the mappacks and not the game.

**Comment by MinDC249** [comment]
Sorry for the English skill but I don’t agree. Then if Alesan thinks that is not a bug he should closed it a long time ago

**Comment by MinDC249** [comment]
This is two different mappacks, they can’t be mixed like that if doesn’t have any outside influences

**Comment by slambo311** [comment]
> Then if Alesan thinks that is not a bug he should closed it a long time ago

Maybe he just didn't see it
Also, you clearly don't know what the hell you're talking about. They can be mixed with no effort whatsoever. It's not alesan's fault, it's the developers. 

> Say other's grammar skill like trash is very rude, also I have stop report bugs for this project a long time ago, please don’t annoying me anymore, I’m focusing on another project

Dude, I can barely understand a single word of this. Most of the internet is rude, though. Plus, the truth doesn't give a crap about if it's rude or not, your grammar's terrible, and you're acting like a 3-year-old.

**Comment by slambo311** [comment]
Also it IS a bug, just with the mappacks and not the game.

**Comment by WilliamFr0g** [comment]
Actually, mappacks getting The Hidden Ones's font data is a moderately well known bug. It only seems to happen with The Hidden Ones, but I'm sure it's a bug with the game. I think it happens because the game doesn't fully reset the map data when switching, and it's probably related to using the onlinemappacks folder, but I can't say for sure.
Also I don't think english is his first language, try not to bother him about it.

**Comment by WilliamFr0g** [comment]
@slambo311

**Comment by slambo311** [comment]
> Also I don't think english is his first language, don't be rude.

Good point.

**Comment by MinDC249** [comment]
That is the true

**Comment by MinDC249** [comment]
Next time you should think before send a bad message, especially when it contains some words that offend others
