### ISSUE TITLE
Update to the latest Love2d to get highdpi (Retina display) support?

### ISSUE THREAD

**Issue by magnusviri** [alesan99/mari0_ae#321]
I have a Mac with a "retina" display, which means pixels are half as big as normal. Love has a setting for love.window.setMode called [highdpi](https://www.love2d.org/wiki/love.window.setMode) that is supposed to deal with this. I fiddled with it and if I turn on highdpi things improve but not with the mouse. It looked like it would need a lot of modifications to get the mouse to work right, which seemed off to me. So I tried the newest version of Love2d, 11.3, and it appears these issues are fixed without modifying the Mari0 source code.

However, a lot of other things went wrong.

So my question is, what are the plans to move to the latest version of Love2d?

**Comment by WilliamFr0g** [comment]
I'm not under the impression it's planned at all; Alesan has declined the suggestion before, and he's also on somewhat of a break from working on AE right now

**Comment by magnusviri** [comment]
I would be willing to do the work if the work was accepted. I doubt I'd finish any time soon because I have very little time. But a year or 2 back I worked quite a bit on Mari0 CE redoing stuff. I didn't tell anyone about what I was doing and so that work wasn't accepted. So I'm hesitant to do any work this time around without discussing it first. What would I have to do to make sure the work will be accepted?

**Comment by magnusviri** [comment]
I just grepped the project for api changes listed on the [10.2 to 11.0 changes](https://love2d.org/wiki/11.0) and here's what I found present or possibly present in Mari0.

- Renamed love.errhand to love.errorhandler. If love.errhand is defined and love.errorhandler isn't, it will continue to work.
- Deprecated love.filesystem.exists (use love.filesystem.getInfo instead).
- Deprecated love.filesystem.isFile (use love.filesystem.getInfo instead).
- Deprecated love.filesystem.isDirectory (use love.filesystem.getInfo instead).
- Deprecated love.filesystem.getSize (use love.filesystem.getInfo instead).
- Removed the default source type for love.audio.newSource
- Removed Source:isStopped and Source:isPaused. Use Source:isPlaying instead.
- Removed Source:rewind. Use Source:stop or Source:seek(0) instead.
- Removed Source:resume and love.audio.resume. Use Source:play and love.audio.play instead.
- Removed variant of love.filesystem.newFileData which takes base64 data, use love.data.decode instead.
- Removed Image:getData and Image:refresh, use Image:replacePixels instead.
- Removed love.graphics.newScreenshot, use love.graphics.captureScreenshot instead.
- Removed SpriteBatch:setBufferSize, spritebatches now automatically grow when they run out of space.
- Removed love.window.isCreated (use love.window.isOpen instead).
- Changed all color values to be in the range 0-1, rather than 0-255. This affects the following functions:
	love.graphics.setColor, love.graphics.setBackgroundColor, and love.graphics.getBackgroundColor.
	SpriteBatch:setColor and SpriteBatch:getColor.
	ParticleSystem:setColors and ParticleSystem:getColors.
	love.graphics.clear.
	The colored text variants of love.graphics.print, love.graphics.printf, Text:set, Text:add
	love.graphics.points.
	ImageData:setPixel, ImageData:getPixel

Not sure:
- Renamed all get[Object]List functions to get[Object]s. 
- Removed the no-argument variant of Text:set, use Text:clear instead. 

Other changes
*Changed high-dpi functionality to require much less code (often none at all) for graphics to appear at the correct sizes and positions.* (this is what I want)
Windows XP is no longer officially supported.
Changed love.graphics.print and friends to ignore carriage returns.
Changed the matrix variant of Shader:send to interpret the matrix as row-major by default, instead of column-major.
Changed the variant of Canvas:newImageData which accepts x/y/width/height to also require slice and mipmap index parameters, which are used when the Canvas isn't a 2D type or has mipmaps.
Changed some love.graphics, love.window, and love.event APIs to cause an error if a Canvas is active.
Changed stenciling functionality with a Canvas active to require stencil=true (or a custom stencil-formatted Canvas) to be set in love.graphics.setCanvas.
Changed the 'vsync' field of love.window.setMode and t.window in love.conf. It's now an integer with 0 disabling vsync.
Changed Sources to either be playing or not playing, rather than playing, paused, or stopped. Source:stop now pauses and rewinds the Source.
Changed love.audio.pause() to return a list of Sources that have been paused by that call.
Changed Source seeking behaviour, all kinds of Sources now behave similarly when seeking past the boundaries.
Updated Source:seek to work if the Source isn't playing.
Changed love.run and love.errorhandler to return a function for their main loop, which gets called until love quits.
Changed love.keyboard.isDown and love.keyboard.isScancodeDown to error if an invalid enum value is given.

**Comment by magnusviri** [comment]
One last comment for the night. Mari0-CE looks like it is already added Love 11 support. Here's an example of how they dealt with the 1-255 vs 0-1 colorspace and static or stream audio changes. This is from [their main.lua](https://github.com/Mari0-CE/Mari0-Community-Edition/blob/master/main.lua), likes 43-46.

	COLORSPACE = loveVersion < 11 and 255 or 1
	COLORCONVERT = loveVersion < 11 and 1 or 255

	MUSICFIX = loveVersion < 11 and "static" or "stream"

**Comment by Aid0nModder** [comment]
Alesan has stated he won't be porting until LOVE 12 is out.

**Comment by magnusviri** [comment]
Sounds good. I'll close this issue.
