### ISSUE TITLE
cube dispenser shouldn't show hidden enemies

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#335]
it also should have icons next to custom enemies like spawner

**Comment by WilliamFr0g** [comment]
Well to be fair, cube droppers can only drop custom enemies and cubes, so there usually isn't much ambiguity as to what's an enemy and what isn't

**Comment by Aid0nModder** [comment]
true but it still looks odd

**Comment by alesan99** [comment]
41bb5575775fbe23bd1ddfe685dc71b89a062641
