### ISSUE TITLE
"collectscoins" property for custom enemies

### ISSUE THREAD

**Issue by AmyTheCat178** [alesan99/mari0_ae#341]
A property for custom enemies which enables them to collect coins and add up to the player's coin count, similar to how thrown Koopa shells do it in the Mario series. Could also be useful on "helper", NPC type enemies or ones used with custom characters.

**Comment by alesan99** [comment]
8a9184d9dc34ffdf8d1ca35b03bcd2b39fa8b7af
4a42275caa34ec612064b62906e34829f04d1490
