### ISSUE TITLE
Classic game mode without portals

### ISSUE THREAD

**Issue by lucamosca1** [alesan99/mari0_ae#344]
Amazing job, really!
I'd like to know if in some way is there possible to have the standard gameplay without portals feature.

Hope this enhancement could be insert in roadmap :)

l

**Comment by Aid0nModder** [comment]
That exists
![image](https://user-images.githubusercontent.com/71894636/148106269-b99a379c-c11a-4ca7-ae1a-7426e04f4b63.png)

**Comment by WilliamFr0g** [comment]
It's also an option in mappacks

**Comment by lucamosca1** [comment]
Will it be possible to consider it as option without completing the game first? :)
Just an idea otherwise you can close the "issue"

Thanks

**Comment by alesan99** [comment]
If you don't want to complete the game all you have to do is type in the konami code on the titlescreen or skip to the final level in the level editor, its real easy
