### ISSUE TITLE
Custom enemy platforms can't carry a player with star power

### ISSUE THREAD

**Issue by skysometric** [alesan99/mari0_ae#355]
Steps to reproduce: an enemy with

```
	"platform": true,
	"platformchecktable": ["player"],

	"resistsstar": true
```

cannot carry a player that is invincible from a star. In most cases, the player passes through the enemy without collision; if the platform is moving up, the player is carried by the platform but stuck in a glitched state where they cannot jump.

https://user-images.githubusercontent.com/11470715/156939517-d1b431e5-da36-4839-94a9-8dae00d8c203.mp4

**Comment by WilliamFr0g** [comment]
You need to set solidkill to true

**Comment by skysometric** [comment]
not exactly intuitive, but it works, thanks!
