### ISSUE TITLE
[BUG] on/off colored block not all being updated if triggered on same frame

### ISSUE THREAD

**Issue by Plouni** [alesan99/mari0_ae#357]
![Bug_blocks](https://user-images.githubusercontent.com/28339894/157127480-8ff17e82-8228-4bef-997f-f87c3eddff81.gif)
When several on/off block of different colors are being triggered on the same frame, only one color is being updated. It worked perfectly fine before

**Comment by alesan99** [comment]
Caused by changes to thwomps. Fixed
cce6da3ef04092e1fce3468618bed7d9edf1c100

**Comment by Plouni** [comment]
Thanks a lot! That was fast, I saw that you even put out a patch for this! You're the best ;)
