### ISSUE TITLE
Star music plays over regular music

### ISSUE THREAD

**Issue by skysometric** [alesan99/mari0_ae#358]
When the player gets a star (with the built-in star or otherwise), the star music plays on top of the regular level theme. This bug only occurs in v13e.

**Comment by alesan99** [comment]
Could you provide more details? Can't seem to get this to happen on smb 1-1.
I've had this happen with animations and music changers in the past but I want to know if this is something seperate.

**Comment by alesan99** [comment]
No idea if this still happens

**Comment by Aid0nModder** [comment]
It plays over intermission music, idk if that is what sky was on about but i've had zero problems with normal music
