### ISSUE TITLE
Additional settings for region triggers

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#36]
Currently, region triggers can be set to trigger upon the player, an enemy, or both, entering the region trigger. I propose a new menu system, and additional options for region triggers.

Options are now presented as checkboxes rather than a dropdown menu. Options could include:

- Player
- Enemies
- Cubes
- Energy Balls
- Lasers
- Light Bridges
- Funnels

This would give region triggers some more flexibility and usefulness for map design.

**Comment by WilliamFr0g** [comment]
This sounds like the large number of options would take up more space in a level file than necessary, especially if it's expanded to not just include portal stuff. You can already set region triggers to detect specific object types, though not with the menu. That would work for all physical objects, and there are already dedicated laser detectors. Nothing yet for funnels though.

**Comment by Aid0nModder** [comment]
in ACE i just made it an input, also you could put any object followed by a "," to add more, I'll port it over if Alesan is fine with that.

**Comment by alesan99** [comment]
02d6fe931f3430a34bfa409f94cdf76a69b3cd09
