### ISSUE TITLE
[Suggestion] "force enable dropshadows" nitpick

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#362]
So basically, some options to force enable or force disable map settings like drop shadow, underwater, intermission, etc. It'll allow players to enable/disable map settings for all maps at once, and also set it back to its original state, speeding up the process of map setting changing dramatically. I'm gonna be real, people who like drop shadows like me will definitely love this feature.

**Comment by alesan99** [comment]
This is preeetty niche. Not to mention it will also not work very well as it will likely break a lot of mappacks. You're better off using a program to replace all the settings across all your mappack files yourself, it's all plain text so it's would be simple.

The only things I'd actually consider adding is a "force dropshadow" nitpick (which might already be a thing sort of? I'll have to check) and maybe a "skip intermissions" nitpick

**Comment by slambo311** [comment]
Alright. The dropshadows do already break some mappacks (such as the smb3 and smw levels), but alright. Maybe a whitelist/blacklist thing would help with that, though.

**Comment by alesan99** [comment]
The point is that those mappacks have dropshadows disabled already, you can only mess them up if you go into the editor.
45575eaf0a219806f253084e9fe6c7607eb57e75
