### ISSUE TITLE
SMM Sound Updates/Additions

### ISSUE THREAD

**Issue by TheMushrunt** [alesan99/mari0_ae#366]
I'll provide lists to make things easier:

SOUNDS THAT SHOULD PROBABLY BE UPDATED TO THEIR SMM2 COUNTERPARTS OR FIXED FROM THE CURRENT VERSION OF THE SOUND:

-bumperhit.ogg
-bumperjump.ogg
-key.ogg
-keyopen.ogg
-mushroombigeat.ogg (potentially? the sound was changed in SMM2 but I don't really know if it needs to replace the current one.)
-switch.ogg (current version is a bad rip that I _believe_ was used due to the game not being out by then)

SOUNDS THAT MAY NEED TO BE UPDATED:

-cannonfast.ogg (can't tell if it's directly from SMM's files or not)
-icicle.ogg
-iciclefall.ogg (don't know how the sounds were obtained but I think the cleanest rips should be had so yeah)
-stompbig.ogg (I'm pretty sure I provided this to you, and it was obtained via the Switch's built in video capture, so I'd rather update it than have it left with potential issues)
-thwompbig.ogg (current version sounds a bit off to me)

OTHER SOUNDS I THINK SHOULD PROBABLY BE UPDATED TO SMM VERSIONS:

-raccoonswing.ogg/raccoonplane.ogg (they sound pretty weird in their current state, I don't think they were ripped properly from SMB3)
-shuffle.ogg (I can't really tell how good the current version is because shuffle.ogg is a very inconsistent noise, sometimes it loops, other times it doesn't.)

SOUNDS I THINK SHOULD BE ADDED:

-buzzyhelmet.ogg (obtaining a Buzzy Beetle Shellmet)
-spinyhelmet.ogg (obtaining a Spiny Shellmet)
-statue.ogg (turning into a Statue while Tanooki)
these sounds aren't really required but I do think they'd be nice for people who wanna replace specific sounds without it being a bit weird. also I think it's kinda weird that getting a Buzzy Shellmet plays the sound that would be used for hitting something with a Spiny Shellmet.

I can provide any sounds if needed, since I can rip any SMM2 sound at this point in time.

**Comment by alesan99** [comment]
I think most of these sounds are fine during gameplay so I won't put work into it myself, but you can go ahead and upload better versions if you want and I'll put them in

**Comment by WilliamFr0g** [comment]
These fall into the category of "microscopic accuracy fixes". Mari0 is only distantly related to SMM2, it doesn't need to become a carbon copy, and the current sounds aren't even the slightest bit offensive. They definitely don't need updating because you "can't tell if they're directly from the files or not".

**Comment by Alexis0159** [comment]
I have always wanted to have the original sound effects of SMM2 but I can't find them anywhere on the net, I only get the game music in OST but they don't include the sound effects, I guess they record them directly from the game muting the music later they separate them with an audio editor which takes some time to do too. Not everyone has a nintendo switch and a good pc to be able to run the emulator and record them from there
