### ISSUE TITLE
4XBR Shader Broken at Some Resolutions

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#373]
The shader for the 4XBR pixel art upscaler is broken.
This is how the game looks without it:
![image](https://user-images.githubusercontent.com/29778535/160625569-acafe987-29ea-48e0-9e00-3bc86f68cd3e.png)
And this is how it looks with it:
![image](https://user-images.githubusercontent.com/29778535/160625604-ceeed549-e37b-40f4-8255-b0f908129522.png)
See all of those weird artifacts? This is what it's roughly supposed to look like:
![Fixed](https://user-images.githubusercontent.com/29778535/160627631-e1c27dd0-93b7-45e1-af1d-9ac3a4713265.png)
This was achieved by locally upscaling from a 1x (400x224) screenshot and downscaling the resulting image back to 1366x768.

This issue is only present with certain "scale" settings. To be specific, 3X and Full Screen. In 1X, 2X and 4X, the filter works perfectly fine. Resizable is fine too, until you try going into full screen.

**Comment by WilliamFr0g** [comment]
This is also because you didn't set your high dpi settings (look at my comment on your other graphics related issue)

**Comment by poudink** [comment]
As with the other issue, I'm not using Windows so that doesn't really apply here. This is also fixed the native window manager full screen mode though, so I guess I can also close this.
