### ISSUE TITLE
Thwomps Can Get Stuck in Portals

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#374]
![image](https://user-images.githubusercontent.com/29778535/160633432-156ca339-d648-479b-af69-fbdf1253cea7.png)
A Thwomp going through a Portal which has its exit facing the same way as its entrance will get stuck oscillating very quickly between the two portals. This is because the Thwomp's trajectory isn't being redirected by the Portal. In this screenshot for example, the Thwomp was going to the left when entering the blue portal. When exiting from the orange portal, the Thwomp kept trying to go left, thus instantly re-entering the portal. This happens with Thwomps going any direction, but looks the weirdest with Thwomps getting back from an attack. When they're attacking, they have enough momentum going through the portal to prevent them from weirdly oscillating at the portal entrance. The solution would be to change the Thwomp's trajectory to match the direction of the exit portal.

**Comment by alesan99** [comment]
Didn't quite make them change trajectory, but I made sideways thwomps more consistent with how normal thwomps behave with portals
ca23f2a1d3fe71c0cb92998a612dcf2a4abcc69c
