### ISSUE TITLE
[Feature Request] Improved Scrolling

### ISSUE THREAD

**Issue by poudink** [alesan99/mari0_ae#375]
This was also an issue with the original Mari0, but this game unfortunately commits the cardinal sin of 2D sidescrollers: Keeping most of the camera's field of view on the opposite side of the direction the player's moving in, despite most of that information being totally useless. After all, what the player really needs to see is what's present in the direction he's going towards. The camera doesn't start scrolling right until the player's passed about two thirds of the screen:
![Right Scroll](https://user-images.githubusercontent.com/29778535/160638698-052a24ed-67fb-4d53-bc8e-8277c14f43dc.png)
It's even worse when going left:
![Left Scroll](https://user-images.githubusercontent.com/29778535/160639600-6435c2ba-350c-4e71-93ad-3e4a20a58360.png)
Vertical scrolling is also affected:
![Up Scroll](https://user-images.githubusercontent.com/29778535/160641750-2ae4dec9-999d-47bf-a82e-3f1420337938.png)

**Comment by alesan99** [comment]
It's a side effect of turning the game widescreen while also trying to remain faithful to smb's visibility range.
Vertical scrolling has the challenge of dealing with jumping (don't want the camera constantly rocking up and down with every small jump) and having to work with levels that were designed to go up or down OR levels where moving vertically isn't the goal.
Should also be noted that there are slower-paced levels and puzzles that make use of the current camera behavior. 

Luckily, the centered camera option in the editor alleviates this a bit which you may like. Though there isn't an option to forcefully enable it throughout all mappacks. I can add this through the hidden nitpick.json settings https://stabyourself.fandom.com/wiki/Nitpicks

**Comment by alesan99** [comment]
`{"centerCamera": true}` in nitpicks.json
860b571bc69b9e983514711baa49ecc30a3fdf06
