### ISSUE TITLE
[Suggestion] Extra background layer features

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#376]
Here's a list of features I came up with that have to do with the background layer:

- Placing entities in the BG layer makes the entity only collide with tiles or other entities in the BG layer.
- An extra layer that's in front of both the foreground and background layers, allowing mappack makers to basically hide objects (ex: a goomba hidden behind a bush, pillars in a castle level, etc.)
- Customizable darkness for each layer, so players can more easily tell the difference between the layers, and so mappack makers don't have to manually make a duplicate of some tiles/sprites just to make them darker. Maybe some sliders for each layer, or just options for "off", "normal", and "silhouette". Plus, maybe add an entity that lights/darkens layers when triggered.
- Toggleable drop shadows for each layer. Honestly, I think this is a pretty bad idea, but whatever.
- Moving mario from layer to layer. I don't know much about lua, but I wouldn't be surprised if this would be a pain to implement, but an idea's an idea. I have two ideas for ways for mappack makers to change mario's layer:
       - A trigger that instantly changes mario's layer
       - Putting a pipe's exit on a different layer than its entrance.

**Comment by WilliamFr0g** [comment]
Foreground tiles that render over things already exist (it's a tile property), and recoloring bg tiles has a little potential. Aside from that, everything here is easier said than done, and every one would require rewriting huge amounts of exiting code in addition to new behaviors; I can guarantee none of it will be added. The current background layer system is rudimentary, nothing more than normal nonsolid tiles that are drawn sooner; expanding on it without completely redoing it is impossible. Not to mention the physics engine isn't built to handle anything of this sort, and anything portal related would be a disaster.

**Comment by alesan99** [comment]
Yeah pretty much what william said.
