### ISSUE TITLE
[Suggestion] Customizable drop shadows

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#377]
Basically, settings that change the angle, distance, darkness, and maybe also color and blur for the drop shadows. Those first three could be useful for some kind of day/night cycle, and the color could be useful for castle levels or something. As for the blur, I don't really know, considering we're talking about an 8-bit game.

**Comment by WilliamFr0g** [comment]
Drop shadows only really exist for people who like SMM, this and your other suggestion would be more suitable for a 3d game in a well coded 3d engine

**Comment by slambo311** [comment]
Fair point.

**Comment by alesan99** [comment]
Yeah hate to shoot this one down too but drop shadows are only optimized for the color they have now. Without adding an entire shader pass, the only viable ones are darkness and angle, and I don't think changing those is all too useful.
