### ISSUE TITLE
[Suggestion] Supersize mushroom ideas

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#378]
- When you right-click something that is supersized, it will bring up a menu that controls how large the enemy will be, if it splits into smaller enemies when stomped on, how many enemies it'll split into, etc.
- If the enemy already has a right-click menu, the supersize menu will be under that menu, to prevent bugs.
- Maybe also add an option for breaking blocks, like a dropdown menu with options for not breaking at all, breaking blocks like bricks, breaking harder blocks like hard blocks, and breaking all blocks (similar to the classic mega mushroom).

**Comment by Aid0nModder** [comment]
Good on paper, Jank in practice. It's not worth it when considering the work it would take, Just use custom enemies.

**Comment by slambo311** [comment]
Good point.

**Comment by alesan99** [comment]
I've made the effort to make every supersized enemy as accurate as I could tell, so all of these seem like they have really niche uses.
If you designed a level that needs these, custom enemies are the way to go.
