### ISSUE TITLE
[Suggestion] Bullet Bill right-click menu

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#379]
Here are some ideas for the menu:

- Changing direction, with multiple directions able to be selected
- Speed slider
- Rate of fire slider
- Block collision dropdown, with options for no collision, exploding on collision, breaking blocks and exploding bullet on collision, and breaking just the block on collision.
- Checkboxes for which blocks it can break (no blocks, regular breakable blocks like bricks, hard breakable blocks like hard blocks, and everything else).
- Radius for how close Mario should be for bullets to home in on him, like the 3D games.
- Time until the bullet explodes (0 for no explosion timer), also like the 3D games.

**Comment by WilliamFr0g** [comment]
I strongly recommend you learn how to make custom enemies

**Comment by slambo311** [comment]
Alright.

**Comment by alesan99** [comment]
Same as the other issue I closed, custom enemies can do these.
I also recommend using cannon balls as they are a little more flexible than bullet bills.
