### ISSUE TITLE
[Suggestion] Clear Pipe/Vactube ideas

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#380]
- Speed slider
- Clear Pipe suck checkbox
- Diagonal pipes/vactubes (like tracks)

**Comment by WilliamFr0g** [comment]
Most definitely not diagonal ones, mari0 doesn't really "have" diagonal things, even the current sloped things are pretty tacky implementations

**Comment by Aid0nModder** [comment]
Aslome mank god slomps anmd diangnal pips

**Comment by slambo311** [comment]
> Aslome mank god slomps anmd diangnal pips

My brain hurts.

**Comment by alesan99** [comment]
The only significant difference between clear pipes and vactubes is the sucking, so I really don't see the point of making them the same.
What William said is true so that leaves only the speed slider. I could see it being nice for nsmb-style pipes but I don't think its all that useful.
