### ISSUE TITLE
[Suggestion] SMM2 slope tiles

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#381]
Honestly, I can't find any DLC that has SMM2 slope tiles, other than the forest and desert style tiles from the SMM2 compilation, but some people want to use the default overworld, underground, castle, and underwater styles. Them being built-in would be a good idea, since I doubt mappack creators want to manually rip the slopes manually, or manually recreate them.

**Comment by WilliamFr0g** [comment]
Just make them yourself or find a tileset on the forums

**Comment by alesan99** [comment]
You can already make any tiles you want.
If a mappack creator doesn't want to copy-paste sprites they found on google then chances are they won't get very far in the mappack making process in the first place.
