### ISSUE TITLE
Change my name to WilliamFrog

### ISSUE THREAD

**Issue by WilliamFr0g** [alesan99/mari0_ae#383]
Because I'm just credited as William and that's a bit ambiguous
(I already talked with Alesan about it and he suggested I make an issue as a reminder)

**Comment by Aid0nModder** [comment]
Granted, I will refer to you as frogWilliam from now on, you're welcome

**Comment by alesan99** [comment]
45575eaf0a219806f253084e9fe6c7607eb57e75
