### ISSUE TITLE
Allow player to cut the death animation and levelscreen short by pressing space

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#40]
Upon dying in Mari0, you must wait about 6 seconds for the death animation and the levelscreen to end. If death isn't common, then it's not a big issue, but in harder mappacks where the player is dying a lot, this can be very annoying. Allowing the player to press space to skip over the death animation, and press space to cut the levelscreen short, would be quite convenient.

Optional: Allow the levelscreen to stay until the player presses space(possibly via per-mappack setting?)

**Comment by alesan99** [comment]
This is already in the game
