### ISSUE TITLE
Close some issues

### ISSUE THREAD

**Issue by WilliamFr0g** [alesan99/mari0_ae#410]
No way all of the 120 other issues are going to get done, just close the ones you won't do

**Comment by Aid0nModder** [comment]
I agree, some of the "wontfix" ones shouldn't stay open, and ones relating to mario maker should go too, this isn't mari0 maker

**Comment by alesan99** [comment]
That's the purpose of the labels, it helps sort through the important issues, while stopping people from reporting the same issues again. While having zero issues listed eventually would be nice, its not all that important to me
