### ISSUE TITLE
Bug wit hitboxes on entity blocks, and moving type of platforms

### ISSUE THREAD

**Issue by Poptap** [alesan99/mari0_ae#418]
[https://youtu.be/tJp_paLZ2yQ](url)

Entity blocks do not match the hitboxes standard blocks, so that the character hits the angle although, but he must move to the side, and in the case of the platforms, they become unplayable, because they may not be registered by the game for some reason.

**Comment by WilliamFr0g** [comment]
Can you unprivate the video

**Comment by Poptap** [comment]
> Can you unprivate the video

oh, okay!

**Comment by Poptap** [comment]
so... what do you think about that?

**Comment by Alexis0159** [comment]
In the last update it seems that the thing about Mario going through the platforms when he falls at high speed had been fixed :o

**Comment by Poptap** [comment]
> In the last update it seems that the thing about Mario going through the platforms when he falls at high speed had been fixed :o

Cool! Now without fear, I can jump to on platforms!

I would like to know more:

So it means the same issue will be fixed with red seesaws?

And what about those entity blocks, that have difficulty with not redirecting a character toward a block?

**Comment by WilliamFr0g** [comment]
I haven't experienced any issues with red seesaws. Entity blocks doing that probably won't be fixed, it's a small bug and Alesan is a busy person

**Comment by Poptap** [comment]
> I haven't experienced any issues with red seesaws. Entity blocks doing that probably won't be fixed, it's a small bug and Alesan is a busy person

About entity blocks: I found at least one entity block (actually found a few already blocks) that also redirects in the other side like normal blocks, namely: frozen coin, p block, button block, and maybe a few more. I'm just saying that maybe you can copy some part of the code from them and paste it into the remaining entity, but I could be wrong, because I'm not a programmer. And I agree with what you said about the smallness of these issues, they can be dealt with later.

About experience I had: Just found these 2 issues from mappack that called: "MPA DEMO", and because of these bugs, these sections in which these platforms were placed became more difficulty and annoyingy.

And about Aelsan being busy: Sounds cool, he's found a job, and takes care of work, at the same time updating this mod.

Well, that's about it, thanks for answering my question, uhm... bye...
