### ISSUE TITLE
Scroll while right-clicking entity to see what it is linked to

### ISSUE THREAD

**Issue by Plouni** [alesan99/mari0_ae#420]
Just port over this feature that was present in Mari0 SE and that I miss so much :'(
![bug_link2](https://user-images.githubusercontent.com/28339894/181627234-dcfd1879-23a5-4d44-8c7d-aeb501ea35b7.gif)

**Comment by Aid0nModder** [comment]
Port isn't an option as the code is entirely different but i can look into replicating it

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/448
