### ISSUE TITLE
Remove sprite fixing in sprite loader

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#437]
I get that backwards compatibility is something you like but the code is awful.

Not to mention how half the time when quads get changed these days they're not fixed. For example when a large number of portal elements got spritesets.

It's just visual and if people have a problem with it they should just change it back themselves.

**Comment by alesan99** [comment]
I don't see the point of having less backwards compatibility. When bad code is hidden away in a file and is rarely executed its not much of an issue
