### ISSUE TITLE
Reflectiveness Tile Property

### ISSUE THREAD

**Issue by AmyTheCat178** [alesan99/mari0_ae#44]
A property for tiles to be reflective, so if the player or any other entity stands on top of a tile with this property, their sprite will appear vertically mirrored under the player or entity. I don't know how good of an idea this is or if it's too complicated, but thanks for reading.

**Comment by alesan99** [comment]
It could be a neat effect but I don't think it's worth the effort.

**Comment by AmyTheCat178** [comment]
Fair enough, thanks for your comment.
