### ISSUE TITLE
Folders for animations

### ISSUE THREAD

**Issue by Plouni** [alesan99/mari0_ae#441]
We have a mappack with more than 1800 animations. It would be a blessing if we could sort animations by folders like how it is possible with custom enemies

**Comment by Aid0nModder** [comment]
Oh boy time to rewrite another function

![sad-baby](https://user-images.githubusercontent.com/71894636/184241437-dbea556a-ca47-42fe-951c-4a604c738f1b.gif)

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/442
