### ISSUE TITLE
Clear pipe-like regular pipe entities

### ISSUE THREAD

**Issue by slambo311** [alesan99/mari0_ae#456]
Self-explanatory. An entity that is placed like the clear pipe, but looks and acts like a regular pipe warp. In the right-click menu, it should let you obviously change where you want the pipe to warp to (World, level, and sublevel). It should also let you change the type of pipe shown (overworld, underground, castle, etc.), and also have a setting to make it suck you in or push you out, similar to certain underwater pipes in NSMB. Plus, different variations of it, such as a "mini pipe" that can only be entered with Mini Mario, also inspired by NSMB.

Other ideas I have for pipe entities:

- Portalibility toggle
- Toggle actually warping or not (when off, another option that allows the player to go into the pipe, but makes the player instantly exit through it)
- Toggle shooting Mario out when exited (similar to SMW and NSMB)
- When another entity is placed in it, the entity will come out of the pipe
     - Toggle shooting the entity out
     - Toggle "respawn" mechanic (similar to Portal droppers)
     - Slider for how many entities should come out of the pipe
          - When the pipe entity "limit" is reached, the entities should stop coming out of the pipe.
               - If the respawn toggle is enabled, it should "respawn" the entities when they aren't present anymore
          - Min 0, Max 10
     - Slider for seconds between spawns (Min 1 second, max 60 seconds)

**Comment by WilliamFr0g** [comment]
God no, you could only suggest anything like this if you had 0 idea how the game works

**Comment by WilliamFr0g** [comment]
How did you find out about Mari0 in the first place?

**Comment by WilliamFr0g** [comment]
Because this is not Mario Odyssey 2D Android or anything like it, it's a mod of a small fangame from 2012, made by one person. This is not Mario Maker, and your suggestions will not bring it to that point. It's not even open to feature requests, and there will be no more major updates.

**Comment by slambo311** [comment]
> God no, you could only suggest anything like this if you had 0 idea how the game works

I'm not THAT dumb. Besides, how the hell was I supposed to know that feature requests and major updates aren't a thing? Didn't say it on the readme, forum post, or anything like that.

**Comment by slambo311** [comment]
Also, says the guy with 37 pull requests, with only 10 merged.

**Comment by slambo311** [comment]
Alright, nevermind, both of those were on the readme, but still. 27 unmerged pull requests.

**Comment by slambo311** [comment]
I may be dumb, but at least my dumb contributions are acknowledged.

**Comment by slambo311** [comment]
It's just a suggestion, though. Plus, we're talking about a game, not politics.

**Comment by WilliamFr0g** [comment]
You haven't made a single PR, and besides Alesan hasn't looked at the GitHub in months to merge anything. He isn't projected to come back until December at the soonest.

**Comment by WilliamFr0g** [comment]
And even then, I only have 16 open pull requests, I renamed all my repositories a few months ago which meant 9 of them got closed and I had to recreate them.

**Comment by WilliamFr0g** [comment]
As for you though, all but one of your issues have been personally shot down by Alesan

**Comment by slambo311** [comment]
Alright, fair point.

**Comment by slambo311** [comment]
I haven't been helping much, but still, in a crappy fork I made, I have implemented a few ideas I've had.

**Comment by Aid0nModder** [comment]
> Also, says the guy with 37 pull requests, with only 10 merged.

Wow, you're a real dickhead

**Comment by Aid0nModder** [comment]
Sorry if you saw them comments, i've had a bad day, the idea has potential but overall is very niche and would be a pain to impliment. Please treat william with a little more respect please, me and him do our best to fix the game but we can't do much while alesan is busy.

**Comment by slambo311** [comment]
Alright, sorry, most of this was me being an idiot anyway.
