### ISSUE TITLE
Double-click sliders to input precise values

### ISSUE THREAD

**Issue by Qwerbey** [alesan99/mari0_ae#46]
When creating levels, it's very difficult to get precise values.  For many cases, this isn't much of a problem, as being off by a few decimal values won't change much.  However, some entities; particularly Delayers, and setups that need precise timing, such as to sync with Animations; will be almost impossible to set properly in-game.

I've had this as a replacement in my own personal mod of Mari0: SE, and it does genuinely make setting up precise entities easier.

I think the simplest way to implement this would be as a Nitpick, but it could also be useful as a hotkey in the editor.

**Comment by alesan99** [comment]
It shouldn't be too hard to make it so every slider has a built in input if you double click it, that'd be my preferred solution

**Comment by LeanneTM** [comment]
i agree with this, itd be useful.

adding to this, i once tried to make wind without speed and while the slider showed 0.00, character was still moving.. veeeeeery slowly :p

**Comment by alesan99** [comment]
Partially implemented for most sliders, you need to right click instead of double clicking c150e1dbac816e3f415de5d16d7a9e1c5392c7b3
