### ISSUE TITLE
Broken with Retina on Mac

### ISSUE THREAD

**Issue by MoonstreamJustNotInSpace** [alesan99/mari0_ae#464]
Basically just that, when set to resizable, the cursor doesn't align with the window, and shaders mess with the scale, making the window 2x scale without actually changing the window, meaning you only see the top right corner of the screen.

**Comment by WilliamFr0g** [comment]
I wouldn't know, but this is not likely something that can be fixed, seeing as the game doesn't do anything wrong in particular

**Comment by alesan99** [comment]
LÖVE has ways to modify its behavior with retina, however I do not have any way to test it and mari0 runs on an outdated version of LÖVE.
I may attempt to fix it but I have a risk of breaking other platforms that currently work fine.

**Comment by alesan99** [comment]
Added Experimental nitpick "DPIFix": true or integer. (enabled in nitpicks.json).
Temporary solution, hopefully it works. Setting it to 0.5 should fix it if it doesn't work when its just set to true
ca23f2a1d3fe71c0cb92998a612dcf2a4abcc69c
