### ISSUE TITLE
Error with rightclicks

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#465]
I'm gonna fix the issue myself, just posting for documentation
![image](https://user-images.githubusercontent.com/71894636/208244388-49698531-6b40-4546-9331-60b63ef90f22.png)

**Comment by Aid0nModder** [comment]
Ok it's an issue with how it handles numbers in dropdown, i was going to fix some issues with that today anyway so i might as well do it now

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/pull/466
