### ISSUE TITLE
"Could not read ogg bitstream" (Crash error message)

### ISSUE THREAD

**Issue by FiremanStan69** [alesan99/mari0_ae#468]
it shows the error "Could not read ogg bitstream" when i launch the game, no idea what i need to do, all i know is that OGG files are audio files, so it may have something to do with that?, other then that, no idea, if you know anything about this, PLEASE help, i really want to play this.

**Comment by WilliamFr0g** [comment]
Can you post the error

**Comment by alesan99** [comment]
![Capture](https://user-images.githubusercontent.com/8108710/213897918-7dce8bf7-1bbf-4d7c-b88a-0aceb3a402c7.PNG)
This was possibly made by this commenter
