### ISSUE TITLE
SMW Flip blocks don't stop spinning correctly

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#48]
In SMW, if you hit a flip block, then stand inside the flip block while its still spinning, it will not stop spinning until the space inside the block is clear. In Mari0, the block will stop spinning regardless of whether something is still inside it, which can lead to enemies getting stuck inside the block, or in extreme cases, allow the player to clip through walls.

**Comment by alesan99** [comment]
Done.
