### ISSUE TITLE
Slope Clips and bugs

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#509]
Some slope bugs found post launch. Will update as I find more
![GIF 12-02-2023 19-29-43](https://user-images.githubusercontent.com/71894636/218332802-656db914-e9bd-4a32-9e0d-18eaf6e06c31.gif)

TipouStar found this bug with slopes and platforms.
![Bug_slope](https://user-images.githubusercontent.com/71894636/218558946-aa742d6a-73ae-48ce-bc81-e366558ba7fe.gif)

**Comment by alesan99** [comment]
All fixed so far
