### ISSUE TITLE
Custom "Hit" Tiles for Bricks/Item Blocks

### ISSUE THREAD

**Issue by Aid0nModder** [alesan99/mari0_ae#519]
The ability to give question blocks a unique hit tile, the smoothest approach would be to make something similar to custom tile debris.
I'm not sure how this would work under the hood and I could imagine this being a pain to implement, hence this issue instead

**Comment by alesan99** [comment]
Planned, just hasn't been the highest priority
https://github.com/alesan99/mari0_ae/issues/35
