### ISSUE TITLE
Crashing game while using text entities 

### ISSUE THREAD

**Issue by LeEpicPasta** [alesan99/mari0_ae#520]
while editing the text entity, pressing CTRL A to select all the dialogue in the text selects every object in the level. If you chose to delete the text, it will also delete everything else in the level as well. Once you exit the text editor the game crashes because the original place where the text originally was no longer exists and the game doesn't like that. It's really annoying and it happens to me on accident way to many times. Fixing both of these bugs would be a blessing for me.

**Comment by LeEpicPasta** [comment]
Minor note, this doesn't happen with just text, but any entity that you can adjust the settings within the entity.

**Comment by alesan99** [comment]
86aac741d2eadeb78e64eb931eec304f92dd74a2
