### ISSUE TITLE
Purple gel bug

### ISSUE THREAD

**Issue by Plouni** [alesan99/mari0_ae#529]
I want to port a mappack from Mari0 CE again and I've encountered 2 bugs with purple gel that make it impossible:
- While **underwater**, right/left wall with purple gel, are really bugged. Once you touch the wall you can't move at all, and you can't jump too because the 'jump' button makes you walk upward for some weird reason
- A character who can double jump, can't use his second jump when walking on a right/left wall with purple gel 

Gif to illustrate what I mean about the underwater purple gel bug:
![bug_purple_gel](https://user-images.githubusercontent.com/28339894/223546557-1c3540d1-b0f8-49c4-9fed-35f4e2175fb9.gif)

**Comment by alesan99** [comment]
3f67b501a61eb29251587635582cf4ae7f4346a4
