### ISSUE TITLE
Transforms with water doesn't always work

### ISSUE THREAD

**Issue by LeEpicPasta** [alesan99/mari0_ae#532]
If an enemy leaves water but skips the frame when they leave the water they don't transform. If the property worked differently and always transforms enemies when they're out water instead of the moment they're leaving water it would function more properly. Same could be said for entering water.

**Comment by WilliamFr0g** [comment]
The game doesn't skip frames, if there are other transforms in play that is likely the issue. The water transforms are supposed to only trigger upon entering and exiting, likely to prevent accidental recursive transforms. New enemies from transforms are completely different from the old ones, and were thus never in the water. You might try passing the `water` property, which remembers if the enemy was in water before.
