### ISSUE TITLE
Navigating an input with arrow keys in right click menu scrolls level

### ISSUE THREAD

**Issue by greatbritdan** [alesan99/mari0_ae#558]
This one is on me, it shouldn't scroll the level when your inputting but it doesn't check for that, will make a PR closer to V13.2
![GIF 24-05-2023 19-21-31](https://github.com/alesan99/mari0_ae/assets/71894636/4284e797-2616-4eed-aab5-7f74ad846731)

**Comment by WilliamFr0g** [comment]
Scrolling right click dropdowns also scrolls through tiles
