### ISSUE TITLE
center better right click menus

### ISSUE THREAD

**Issue by LeEpicPasta** [alesan99/mari0_ae#563]
Sometimes when you right click on an enemy the menu appears offscreen and you have to move the camera more and right click the enemy again in order to access the whole menu. Maybe even add a scrollbar if the menu is too large to fit on the screen as well?

**Comment by WilliamFr0g** [comment]
Right click menus already don't appear offscreen, I don't know what you're talking about. You can scroll while they are open too

**Comment by LeEpicPasta** [comment]
> Right click menus already don't appear offscreen, I don't know what you're talking about.

what do you mean it appears offscreen I can even send you a screenshot of it doing so

**Comment by Aid0nModder** [comment]
Screenshot of issue, i've had this before with built in entities, something to do with it being bigger than half the width of the screen. Valid issue
![Uploading Screenshot_2023-07-09_093600.png…]()

**Comment by alesan99** [comment]
9f41936f632e40e4329724b60f2670ac00b511e2
