### ISSUE TITLE
Tiles below a portal are gliched.

### ISSUE THREAD

**Issue by jstaus** [alesan99/mari0_ae#567]
https://github.com/alesan99/mari0_ae/assets/135499638/59c60698-e4cd-4868-8f79-e24826a39559

**Comment by WilliamFr0g** [comment]
This is unlikely to be fixed, portals are just janky that way

**Comment by Aid0nModder** [comment]
Ducking in general is quite a buggy mess, i guess alesan could do a clear pipe approach where it just doesn't let you unduck below a portal

**Comment by WilliamFr0g** [comment]
I'm sure that won't cause any issues /s

**Comment by alesan99** [comment]
I have no desire to rewrite the portal code at this stage, but I think not allowing unducking below portals could be a good solution since you would only get stuck on un-removable portals.
Still low priority though
