### ISSUE TITLE
Mario's portals reset unexpectedly

### ISSUE THREAD

**Issue by MichalNemecek** [alesan99/mari0_ae#573]
I've noticed that world 3-2 of the Up and Away mappack is impossible, because Mario's portals randomly reset. The same thing happens on the first level of Simile Thoughts. I think it has something to do with the way moving between portals works, as it happens when there is an emancipation grill in the line of sight between the portals.

I'm running version 13.1 (4/18/23)

**Comment by alesan99** [comment]
https://github.com/alesan99/mari0_ae/issues/551
