### ISSUE TITLE
Make fencejumptime longer

### ISSUE THREAD

**Issue by WilliamFr0g** [alesan99/mari0_ae#575]
It's too short

**Comment by alesan99** [comment]
If that's the amount of time it takes to hold onto a fence again after jumping I believe I made sure its exactly the same as mario world.

**Comment by WilliamFr0g** [comment]
It's almost impossible to use a custom character move that involves holding up while in front of a fence, because you regrab it so fast

**Comment by alesan99** [comment]
It should be customizable then I suppose

**Comment by WilliamFr0g** [comment]
I think it's too short in general, the main reason you'd jump on a fence is to go up it faster, and you grab it again way too quickly to gain significant distance
