### ISSUE TITLE
Rework variables.lua

### ISSUE THREAD

**Issue by WilliamFr0g** [alesan99/mari0_ae#583]
Most of the variables in variables.lua are only used once or twice in one file. They are never changed either. Examples include the speed of Bowser's panic animation when the bridge breaks, the color of the basically-invisible emancipation grill threshold rectangle, and how long power lines will stay activated when connected to a pedestal button. I do not see any advantage to them being globals separated into a massive disorganized file, instead of being local variables in the file where they are used. All it does is make it more difficult to locate them if they need to be consulted or changed. Some of them can stay, as they have good reason to be global constants, but a lot of these are not useful on this scale.
![image](https://github.com/alesan99/mari0_ae/assets/83377256/d3249c87-792d-492c-bdd1-b24eedf0230a)
This change is pretty accessory, as it won't perceptibly effect game function, but it would help with readability, and could be implemented over time if new values are needed.

**Comment by alesan99** [comment]
I'm not really a fan of it but at this point there isn't much point to changing it
