### ISSUE TITLE
I can't put mappacks cuz using android 12  = storage problem

### ISSUE THREAD

**Issue by HogMedioScorched** [alesan99/mari0_ae#609]
Just a piece of media

I couldn't put a label because the labels option didn't appeared to me

https://github.com/alesan99/mari0_ae/assets/156556823/6f23dc7a-6bca-44f6-ad7c-f5a846ba49ff

Please fix this storage issue

**Comment by alesan99** [comment]
This is unfortunately out of my hands. I've been waiting for the developers of LOVE2D to fix it, which will hopefully happen in their next release.

**Comment by HogMedioScorched** [comment]
> This is unfortunately out of my hands. I've been waiting for the developers of LOVE2D to fix it, which will hopefully happen in their next release.

Thanks for the info man.

**Comment by MrKareem1980** [comment]
> This is unfortunately out of my hands. I've been waiting for the developers of LOVE2D to fix it, which will hopefully happen in their next release.

@alesan99 When You Update Mari0 Ae On Android ?

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@alesan99

**Comment by MrKareem1980** [comment]
@HogMedioScorched

**Comment by xStormyy** [comment]
> This is unfortunately out of my hands. I've been waiting for the developers of LOVE2D to fix it, which will hopefully happen in their next release.

Are there any updates on this?

**Comment by MrKareem1980** [comment]
@alesan99 @alesan99 @alesan99 @alesan99 
CAN YOU FIX MARI0 AE AGAIN ON ANDROID ?✨

**Comment by HogMedioScorched** [comment]
> @alesan99 @alesan99 @alesan99 @alesan99 CAN YOU FIX MARI0 AE AGAIN ON ANDROID ?✨

Bro chillout, whats wrong with you.
