### ISSUE TITLE
Mario Royal Will Kill You Alesan + you are Noob

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#616]
![Screenshot_٢٠٢٤٠٧٢٢-٠٧٢٨٣٠](https://github.com/user-attachments/assets/673fc551-8387-4162-b316-1a41162e64f5)
![Screenshot_٢٠٢٤٠٧٢٢-٠٧٢٨٢٤](https://github.com/user-attachments/assets/5d2e8fe2-22cf-427a-940f-c409b357597b)

**Comment by WilliamFr0g** [comment]
Don't be rude and harass Alesan, he is very busy and does not exist just to serve your complaints. I think version support is part of the framework anyway and not the game, which Alesan did not make.

**Comment by MrKareem1980** [comment]
> Don't be rude and harass Alesan, he is very busy and does not exist just to serve your complaints. I think version support is part of the framework anyway and not the game, which Alesan did not make.

bro when alesan update mari0 ae for android ?

**Comment by MrKareem1980** [comment]
> Don't be rude and harass Alesan, he is very busy and does not exist just to serve your complaints. I think version support is part of the framework anyway and not the game, which Alesan did not make.

i want to play on android 14

**Comment by MrKareem1980** [comment]
Iam Sorry🥲
