### ISSUE TITLE
I Can't Get Kirby Character 

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#624]
![Screenshot_20240810-004050](https://github.com/user-attachments/assets/e011701d-03d9-44e5-8c31-fad750fa96d6)

**Comment by qixils** [comment]
The kirby character setup is convoluted, you must install it manually from the website (selecting that DLC option will open the website on PC). This may change if the author wishes to submit the components individually.

**Comment by MrKareem1980** [comment]
@qixils iam android user (Android 14)

**Comment by qixils** [comment]
Yep, the APIs to open a URL do not work on mobile so you will have to search it out yourself.
