### ISSUE TITLE
i can't go to org.love2d.android

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#627]
![Screenshot_20240810-052158](https://github.com/user-attachments/assets/115613c0-c6f3-4bbc-8152-99bb6339c01b)
when iam going to (files - Save) I Can't See Another Files

Android 14

**Comment by WilliamFr0g** [comment]
This is not a problem with the game, it is a problem with Android

**Comment by qixils** [comment]
Resolved

**Comment by MrKareem1980** [comment]
Thanks
