### ISSUE TITLE
i can't see cartridge tilt on local

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#632]
![Screenshot_20240810-202332](https://github.com/user-attachments/assets/75a0674e-1014-4bbe-ae30-e7710bfa524e)
![Screenshot_20240810-202324](https://github.com/user-attachments/assets/c01b0be3-b6a1-4b96-81a8-9a89c45edad9)
![Screenshot_20240810-202454](https://github.com/user-attachments/assets/fe218368-c72d-4001-bccc-546e86ab27a6)

**Comment by qixils** [comment]
Fixed by https://github.com/qixils/mari0pository/commit/8369fde174525a1f6fca729626a569ad68e36ea1

**Comment by MrKareem1980** [comment]
thanks!
