### ISSUE TITLE
Save cheat settings to disk

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#637]
![Screenshot_20240811-032557](https://github.com/user-attachments/assets/255bc538-4ed8-4711-854a-568b4231450f)

The options for the cheats are lost when closing and reopening the game.

**Comment by qixils** [comment]
Beat SMB1

**Comment by MrKareem1980** [comment]
@qixils i finished smb1
but when i select mode classic & quite game this mode turned to portal & turned off infinite live & time

**Comment by MrKareem1980** [comment]
https://github.com/user-attachments/assets/69f6704e-80d7-4870-a486-55516df83ad5

**Comment by qixils** [comment]
This is intended behavior but may be reconsidered
