### ISSUE TITLE
change files from data to media

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#638]
![Screenshot_20240811-032700](https://github.com/user-attachments/assets/5e37751e-96a6-4e2e-b4b8-7edb7c9a7e93)
i think it will be good for android user because he can add characters & mappacks

ANDROID > MEDIA > LOVE.TO.MARIO

**Comment by WilliamFr0g** [comment]
He can't "just change it", this is part of the Love2d framework, not Mari0 AE, and it not something Alesan has control over

**Comment by qixils** [comment]
This is a limitation of newer Android devices and not possible without requesting the `MANAGE_EXTERNAL_STORAGE` scope which has security concerns. Use the native operating system's file manager if you need to access it. See https://github.com/love2d/love-android/issues/194 for more information.
