### ISSUE TITLE
Suggestion: Add More Characters & Mappacks On DLC 

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#640]
like those ....
![Screenshot_20240813-002217](https://github.com/user-attachments/assets/f3b9a5db-6909-417a-9a0d-676c78d90804)
![Screenshot_20240813-002211](https://github.com/user-attachments/assets/e8c665f1-b26b-4892-b83b-fc7952f4a97d)
![Screenshot_20240813-002339](https://github.com/user-attachments/assets/f97b9eb7-2002-4033-a047-31f0cd250a92)
& More....

**Comment by alesan99** [comment]
Please direct DLC suggestions to the Mari0pository: https://github.com/qixils/mari0pository
I've also added a link to this repository for future reference.
