### ISSUE TITLE
Bug On Project snes demo

### ISSUE THREAD

**Issue by MrKareem1980** [alesan99/mari0_ae#644]
https://github.com/user-attachments/assets/18c8b4ca-52a0-4209-8a0a-80bb8baf9fcd

how to fix this bug?
![Screenshot_20240813-212020](https://github.com/user-attachments/assets/fdf7a403-28b9-4a66-9d7c-6937726d4570)

**Comment by alesan99** [comment]
Related to color conversion issues https://github.com/alesan99/mari0_ae/issues/643
