### ISSUE TITLE
21:9 resolution

### ISSUE THREAD

**Issue by emanuelect** [alesan99/mari0_ae#650]
I tried the game with my 3440x1440 ultrawide monitor, but I noticed that the aspect ratio gets stretched if I remove the black bands. Could you make the game compatible with ultrawide resolution? It would be great to be able to play Super Mario like this.

**Comment by qixils** [comment]
There is an experimental `width` variable in the main.lua you can play around with. One of the nitpicks allows you to set 4:3 aspect ratio but not an arbitrary number so you would have to edit the code to try it.

**Comment by emanuelect** [comment]
Thank you very much, it worked. Playing it I understood what you meant about the camera:
![image](https://github.com/user-attachments/assets/9d695233-efa3-416f-839f-06f861b1e9a2)
![image](https://github.com/user-attachments/assets/b23b0c3b-b1bb-486f-a7be-bdbe4666a248)

But even so it is great fun to play.

**Comment by emanuelect** [comment]
I solved it. I am not a programmer, but thanks to chatgpt after a whole day of trying I managed to fix the camera edited game.lua file.

**Comment by alesan99** [comment]
This is already supported in [nitpicks.json](https://stabyourself.fandom.com/wiki/Nitpicks).
```
"windowWidth": 25,
"windowHeight": 15,
```
The camera issue can be fixed by adding the center camera nitpick
`"centerCamera": true,
`

This won't be supported in any more capacity than this due to the gameplay changes it causes.
