### ISSUE TITLE
Check if pickup regions get deleted after custom enemies die

### ISSUE THREAD

**Issue by alesan99** [alesan99/mari0_ae#88]

**Comment by WilliamFr0g** [comment]
There are some edge cases where the userect won't be deleted. There should probably be a fallback check, so if a userect's owner is deleted, it should be removed too when it updates next.

**Comment by alesan99** [comment]
Yeah I don't think its going to be a hard fix

**Comment by WilliamFr0g** [comment]
I added a check for this in the camera fixes request, so it should be fixed if you add that

**Comment by alesan99** [comment]
3b5c80d849c45cada008e4af39503077f5ad21e7
