### ISSUE TITLE
Health System Improvements/Tweaks

### ISSUE THREAD

**Issue by TheMushrunt** [alesan99/mari0_ae#90]
to me it seems like the health system is a bit...sloppy?
i really feel like it could use a bit of additions/changes to make it feel less limiting.
some examples (with name ideas):
-"HealthWithPowerups": as simple as it sounds. i feel like if a character (with health) collects a power-up with this enabled, it would allow them to have the abilities from said power-up, with the addition of one extra health slot. upon damage, they would simply lose the power-up and the extra health slot would be taken away.
-"ClassicHealth": basically the super mario bros. 2 style of the health system. if the player reaches one health with this enabled, they become small. this should be able to be used with "HealthWithPowerups" though. maybe it should allow any power-up greater than a super mushroom to give extra health without it being taken away from damage, though.
-"MaxHealth": used with "ClassicHealth" to set a limit to how many times the health can be increased. if the limit is less than "Health" then there wouldn't be a limit.
-"CarryOnNewStage": (powerup/hp/maxhp/all) upon loading a new stage (this would be excluding the "Load Level Instantly" animation), the power-up, health, max health, or all of them, would be carried over from the previous stage they were in. anything that isn't enabled to be carried would be reset. in order to prevent issues with older characters, this value should be set to "hp" by default.

**Comment by alesan99** [comment]
It's not sloppy, it was just meant to be an alternative for characters with only one form (Otherwise link and the SMM costumes would die in one hit)
But while replicating smb2 health wasn't the intention, it wouldn't hurt to add these.

**Comment by WilliamFr0g** [comment]
Powerups and hp already transfer between stages, although an option to not reset to defaultsize could be useful. It doesn't sound like max hp can be changed from your post, so that probably doesn't need to be an option.
