### ISSUE TITLE
(MacOS) Command Key alternative for Control Key (Level Editor)

### ISSUE THREAD

**Issue by TheMushrunt** [alesan99/mari0_ae#93]
it feels a bit unnatural to switch between Mari0 AE and another application because Mari0 uses the Control key for its commands, when the other application uses the Command Key. as a solution, it should be possible to just add a check for the Command Key within the editor code on top of the Control Key.
the only problems with this would be that:
-there's a possibility that other OS's have the key mapped to something else with a completely different purpose
-i'm not sure if LÖVE can detect the Command Key

**Comment by alesan99** [comment]
Most keyboards outside of apple don't have a command key afaik so it shouldn't cause any issues. And i assume love should be able to detect it.

**Comment by alesan99** [comment]
#98
