### ISSUE TITLE
Reflection Gel

### ISSUE THREAD

**Issue by Critfish** [alesan99/mari0_ae#99]
In Portal 2, there exists an unused gel called Reflection Gel. It would reflect any lasers that touch it, like a mirror.

In Mari0, lasers are axis-aligned, and there is already a Mirror tile property that reflects portal shots, so Mari0's Reflection Gel could reflect portal shots like mirror tiles. The gel would be gray in color.

**Comment by alesan99** [comment]
This isn't a bad suggestion but I don't think I'll add it.
